### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by 21Philip** [ITU-BDSA2024-GROUP23/Chirp#88]
The new features have created a lot of warnings in our codebase. These have to be handled.

Acceptance criteria:

- [x] No more warnings when building

**Comment by victormemborg** [comment]
@21Philip @Kanerix 

I’ve added a service layer to the application. Exceptions from the repositories can now be propagated, but ensure they are properly handled within the service layer. We should refactor the service layer to accommodate more generalized functionality across the different pages. An example of the cohesion between a repository, service, and page is demonstrated in UserService.cs, specifically in the "GetUserDTO" method on line 21. Instead of managing the logic directly in the UserTimeline page, it is now centralized in the service layer.

**Comment by 21Philip** [comment]
@victormemborg  @Kanerix 

Im currently working on containing the User class within its respective repositories. Instead we will only be using UserDTO's around our services and page-models. This should fix the remaining warnings and ensure consistent error handling. It is a major refactor tho, so be careful about making changes in the DTO's, repositories, services and models until 'refactor/user-dtos' is merged. Otherwise we will have a conflict hell on our hands. I hope to be finished by tommorrow.

**Comment by victormemborg** [comment]
> @victormemborg @Kanerix
> 
> I hope to be finished by tommorrow.
